---
apiVersion: v1
kind: Service
metadata:
  name: geoip
spec:
  ports:
  - name: web
    port: 8080
  selector:
    name: geoip

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: geoip
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: geoip
  template:
    metadata:
      labels:
        name: geoip
      annotations:
        "prometheus.io/scrape": "true"
        "prometheus.io/path": "/actuator/prometheus"
        "prometheus.io/port": "8080"

    spec:
      containers:

      - name: geoip
        image: ghcr.io/observabilitystack/geoip-api:latest
        resources:
          requests:
            cpu: "100m"
            memory: "1Gi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        ports:
        - containerPort: 8080
          name: web
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          failureThreshold: 20
          periodSeconds: 3
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: geoip
spec:
  rules:
  - host: geoip.${HOSTNAME}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: geoip
            port:
              name: web
