name: geoip-api ci build

on:
  push:
    branches:
      - master
      - main
      - feature/**
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: temurin
        cache: 'maven'

    - name: Build JAR from Maven
      run: mvn --batch-mode --no-transfer-progress  clean verify -Drevisison=$(date +%Y-%V)

  docker:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - uses: actions/checkout@v2

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        build-args: |
          MAXMIND_LICENSE_KEY=${{ secrets.MAXMIND_LICENSE_KEY }}

  native:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - uses: actions/checkout@v2

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        file: Dockerfile.native
        context: .
        push: false
        build-args: |
          MAXMIND_LICENSE_KEY=${{ secrets.MAXMIND_LICENSE_KEY }}
