name: "Code Analysis: Docker Slim"
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - id: docker-slim
      name: Run Docker Slim
      run: |
        docker run --rm \
          -v /var/run/docker.sock:/var/run/docker.sock \
          dslim/docker-slim:1.37.0 \
          build --pull ghcr.io/observabilitystack/geoip-api:latest
